### ISSUE TITLE
Y Axis Labels Get Clipped

### ISSUE THREAD

**Issue by philmodin** [misyobun/MSBBarChart#11]
Having large values on the y axis clips the labels.

![IMG_8617](https://user-images.githubusercontent.com/18331871/84223968-389c4780-aa90-11ea-8b61-dd0715019fdf.jpg)

**Comment by misyobun** [comment]
@pvmodin 
Thank you for confirmation.
This issue was fixed in ver 1.0.7, so You can try it.

**Comment by philmodin** [comment]
@misyobun That did it. Thank you!

**Comment by philmodin** [comment]
Uh oh, sometimes the top label gets clipped.
In this case 100 gets clipped, but 200 doesn't.

![label clip](https://user-images.githubusercontent.com/18331871/84331253-91c2b480-ab3e-11ea-8029-a98731613b01.gif)

**Comment by misyobun** [comment]
oh... I had to consider calculation of the y-axis value after shaping.

@pvmodin 
Thank you for reporting.
This problem was fixed in ver 1.0.8, so You can try it.

## Before
![before2](https://user-images.githubusercontent.com/509448/84337054-a56c2a80-abd3-11ea-82f5-2a0225127605.gif)

## After
![after6](https://user-images.githubusercontent.com/509448/84337069-aef59280-abd3-11ea-9da5-a728f99738a1.gif)

**Comment by philmodin** [comment]
That fixed it. Thank you!

**Comment by philmodin** [comment]
Just noticed the yAxisTitle gets clipped.

![image](https://user-images.githubusercontent.com/18331871/84359341-5693a600-ab7d-11ea-99d8-f669eba83b36.png)

**Comment by misyobun** [comment]
@pvmodin 
thank you for notice.
This problem was fixed in ver 1.0.9, so you can try it.

## After
<img width="414" alt="スクリーンショット 2020-06-11 17 20 55" src="https://user-images.githubusercontent.com/509448/84362385-204f3880-ac08-11ea-8513-6c2971aed4d9.png">

**Comment by philmodin** [comment]
@misyobun Wonderful, thank you.
